### PR TITLE
Update LICENSE

### LINKED ISSUE #3: Update LICENSE

### PR DESCRIPTION
**Pull request by fm75**
Fixes #3

### CODE REVIEW

**Comment by Carreau** [comment]
Pushed a commit that changes the date back to 2016.

The date should be the date of first copyright, if there is a single
date it is implicitly YYYY->present.


We also need @yuvipanda to +1, we can't just take his copyright.

**Comment by yuvipanda** [comment]
Whoops, missed this one. Thanks for the ping, @willingc! and thanks for the patch, @fm75 (and the fixup, @Carreau)!

**Comment by fm75** [comment]
Happy to help. btw. did 30 PRs at jupytercon sprint. 6 still open, 20 accepted, 4 closed. All but one were pure legal/license. 
Really happy to make a contribution, even as small as they were.

**Comment by fm75** [comment]
Also made one after that for nbgrader that was merged - resolved an open issue. :)

**Pull request merged**
